### ISSUE TITLE
working past 2 mirons

### ISSUE THREAD

**Issue by awmann** [hpparvi/ldtk#11]
ldtk appears to fail when trying to estimate limb-darkening parameters past 2-3 microns. I assumed this was actually an issue with the Husser models, but the version I have go out to 5.5 microns, suggesting the issue is with ldtk.

**Comment by pearsonkyle** [comment]
Can confirm, I am having trouble generating coefficients within the Spitzer IRAC bandpasses

**Comment by hpparvi** [comment]
I had completely forgotten about this, sorry! I'll look into this tomorrow.

**Comment by hpparvi** [comment]
Can you give me an example of a specific intensity spectrum going out to 5.5 microns? The latest SI data that I know (and what LDTk is using) is the original one announced here

http://phoenix.astro.physik.uni-goettingen.de/?p=102

**Comment by awmann** [comment]
You're right; weirdly the spectra go to 5.5 microns, but the specific intensities only go to 2.6 microns. I don't quite understand why these differ, but the Phoenix group should be able to calculate the intensities out further if they generated the spectra. BT-SETTL (https://phoenix.ens-lyon.fr/Grids/BT-Settl/) seems to go considerably further (~10 microns) for their spectra, but I don't see specific intensities at all.
I'll write them an email and see.

**Comment by awmann** [comment]
From Tim Husser:
Unfortunately, to extract the specific intensities, I'd have to run Phoenix again and I haven't done that in 5 years or so. Problem is that our computing department changed quite a lot during that time (new compilers, new job system, etc). Since we also would like to change some things, I started working on this, but haven't finished yet (and don't see any spare time to do so in the near future). So all I can offer you at the moment is to let you know whenever I get everything running again.

**Comment by awmann** [comment]
If I can get the specific intensities, can you add them? I got the Phoenix group to generate them.

**Comment by hpparvi** [comment]
Hi Andrew,

This is great news! I can make sure LDTk works with the specific intensities if you're storing them locally, and I can add full support for downloading only the needed files if the new spectra can be hosted somewhere (preferably in a FTP server).

**Comment by awmann** [comment]
Here's a test one: 
http://trash.husser.de/lte06000-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-SpecInt.fits
is that format good? Note the headers need fixing.

**Comment by hpparvi** [comment]
Yes, the file format is the same as before and the most important information is already in the header. I can make LDTk to parse the stellar parameters from the filename if they're not available in the header. 

Adding support for these spectra should not need any major changes, so I might be able to do it this week. Is the whole dataset accessible somewhere?

**Comment by awmann** [comment]
Awesome. 
Not fully ready yet. Tim is generating a few and I'm checking to make sure they don't look crazy before he makes the whole set. It might take a while to get the full grid.

**Comment by hpparvi** [comment]
Ok, excellent. If Tim is doing this, he might be able to host them in the same FTP as the old spectra. Keep me in the loop so I can make sure LDTk can use the new grid as soon as it's ready.

**Comment by awmann** [comment]
It should all be here:
ftp://phoenix.astro.physik.uni-goettingen.de/v3.0/SpecIntFITS/

**Comment by hpparvi** [comment]
Beautiful! Please checkout branch v1.5 and install. LDTk willl use the new spectra if you initialize LDPSetCreator with argument ``dataset='visir'``. I'll merge this to the master branch when I'm sure this doesn't break anything for anyone.

These spectra are twice as large as the old ones, but I'll create a binned "lowres" version of the dataset the way I did with the old spectra (I'll try to get this done this week).

**Comment by awmann** [comment]
I just ran a few tests on systems we have already analyzed, and the output parameters are pretty close to my expectations. I'd say it's working properly!

**Comment by hpparvi** [comment]
Excellent! I'll do some more tests this week and create a new release, but feel free to start using the v1.5 branch already.

I'll also ask Tim if he's ok hosting the low-res versions of the new spectra, in which case the ``dataset`` argument will have four options in v1.5 (vis, vis-lowres, visir, visir-lowres).
