### ISSUE TITLE
No module named 'semantic_version'

### ISSUE THREAD

**Issue by vedad** [hpparvi/ldtk#17]
Hi Hannu.

I'm having a problem I'm hoping you could help me with. I installed `ldtk` v1.4.1 on MacOS Mojave 10.14.3. My python version is 3.7.4

When I do `import ldtk` I get the error message

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-7b498706d820> in <module>
----> 1 import ldtk

~/Software/anaconda3/lib/python3.7/site-packages/ldtk/__init__.py in <module>
     18 """
     19 
---> 20 from .version import __version__
     21 from .ldtk import LDPSetCreator, LDPSet, load_ldpset
     22 from .filters import BoxcarFilter, TabulatedFilter, sdss_g, sdss_r, sdss_i, sdss_z, kepler, tess

~/Software/anaconda3/lib/python3.7/site-packages/ldtk/version.py in <module>
     18 """
     19 
---> 20 from semantic_version import Version
     21 
     22 __version__ = Version('1.4.1')

ModuleNotFoundError: No module named 'semantic_version'
```

Do you know what may cause this?

**Comment by tamimfatahi** [comment]
@vedad I recommend installing semantic-version 2.8.5 (latest one & works w/ ldtk).

**Comment by hpparvi** [comment]
Hi Vedad,

Do as Tamim suggested and install semantic_version. I had forgotten to add this as a dependency, but Tamim has solved this now.

Cheers,
Hannu

**Comment by vedad** [comment]
Duh, thanks a lot for the swift replies. I had already tried to search for it with `pip search semantic_version` in case there was a package I was missing, but couldn't find it. Didn't realise it needs a dash instead of an underscore!

**Comment by vedad** [comment]
Duh, thanks a lot for the swift replies. I had already tried to search for it with `pip search semantic_version` in case there was a package I was missing, but couldn't find it. Didn't realise it needs a dash instead of an underscore!
