### ISSUE TITLE
NotImplementedError integrate

### ISSUE THREAD

**Issue by odemangeon** [hpparvi/ldtk#31]
I recently had to reinstall ldtk and I thus installed the latest version from pip.
Running my old code, I was surprised to see that with the current code, we can no longer run LDPSetCreator with SVOFilter. It returns an error saying that integrate is not implemented.

Is it an intended behavior or a bug ?

**Comment by hpparvi** [comment]
Hi Olivier,

Thanks for the heads up, this is a bug. I’ll try to find a moment to fix it today.

Cheers,
Hannu

**Comment by hpparvi** [comment]
This should be fixed now both in GitHub and PyPI.

**Comment by odemangeon** [comment]
Hi Hannu,

Thanks for looking into it so quickly.

BTW, just to let you know, I've tried to run LDTk on python3.11 and it failed when I run LDPSetCreator. It was an error generated by multiprocessing, so something that didn't look LDTk related.

Cheers,
Olivier.
